export const STATS_PAGE_ENUM = {
  stBhsi: 'Highest Strike Rates (Innings)',
  stBha: 'Highest Average',
  stBtwt: 'Top Wicket Takers',
  stBberi: 'Best Economy Rates (Innings)',
  stBba: 'Best Averages',
  stTtr: 'Total Runs',
  stTtr100: 'Team Most Centuries',
  stTtw: 'Total Wickets',
  stBber: 'Best Economy Rates',
  stBbsr: 'Best Strike Rates',
  stBbsri: 'Best Strike Rates (Innings)',
  stBfiw: 'Five Wickets',
  stBhs: 'Highest Strike Rates',
  stBmc: 'Most Centuries',
  stBmr6i: 'Most Sixes (Innings)',
  stBm4: 'Most Fours',
  stBmr4i: 'Most Fours (Innings)',
  stBbbf: 'Best Bowling Figures',
  stBmrci: 'Most runs conceded in an innings',
  stBfow: 'Four Wickets',
  stBmf: 'Team Most Fifties',
  stBmr: 'Most Runs',
  stBmri: 'Highest Individual Score',
  stBmr50: 'Most Fifties',
  stBms: 'Most Sixes',
  stBm: 'Maidens'
}

export const ENUM_SERIES_CATEGORY_PAGES = {
  h: 'home',
  n: 'news',
  v: 'videos',
  f: 'fixtures',
  s: 'standings',
  st: 'stats',
  t: 'teams',
  sq: 'squads',
  ar: 'archives',
  ft: 'fantasy-tips'
}
